import { NextRequest, NextResponse } from 'next/server';

// Full catch-all BFF proxy to the Java backend: every /api/* call the
// browser makes is same-origin against this Next.js app, which forwards it
// on to BACKEND_API_URL server-side. Replaces an earlier version of this
// route that only proxied GET /estado/paginado - that left every other
// call (auth, create/update/delete, actuator/info) going straight from the
// browser to the backend's own origin, which needs CORS enabled there and
// a CSP connect-src naming that origin. Routing everything through here
// removes that requirement entirely.
//
// Deliberately BACKEND_API_URL, not NEXT_PUBLIC_API_URL: a NEXT_PUBLIC_
// var is inlined into the client bundle, so httpClient.ts (running in the
// browser) would read the same value and call the backend directly,
// bypassing this proxy - exactly the CORS/CSP exposure this route exists
// to avoid. Confirmed in production: setting NEXT_PUBLIC_API_URL broke the
// app with connect-src CSP violations and a doubled /estado/estado path
// (httpClient's own /estado prefix on top of the full backend URL).
const REQUEST_ID_HEADER = 'X-Request-Id';

interface RouteParams {
  params: Promise<{ path: string[] }>;
}

async function proxy(request: NextRequest, params: RouteParams['params']): Promise<NextResponse> {
  // Read per-request, not module-level: a module-level constant is
  // evaluated once at import time, before tests (or any per-request env
  // override) can set BACKEND_API_URL.
  const backendBaseUrl =
    process.env.BACKEND_API_URL ??
    (process.env.NODE_ENV === 'production' ? undefined : 'http://localhost:8080');
  // No silent localhost fallback in production: a missing env var there is a
  // deploy misconfiguration, and a generic 502 "unreachable" would hide it.
  if (!backendBaseUrl) {
    return NextResponse.json({ message: 'BACKEND_API_URL is not configured' }, { status: 500 });
  }
  const { path } = await params;
  const search = request.nextUrl.search;
  const backendUrl = `${backendBaseUrl}/${path.join('/')}${search}`;

  const headers: Record<string, string> = {};
  const authorization = request.headers.get('authorization');
  if (authorization) {
    headers.Authorization = authorization;
  }
  const contentType = request.headers.get('content-type');
  if (contentType) {
    headers['Content-Type'] = contentType;
  }

  // Correlation id generated by httpClient once per user action - it has to
  // reach the backend for its logs to line up with what the client shows.
  const requestId = request.headers.get(REQUEST_ID_HEADER);
  if (requestId) {
    headers[REQUEST_ID_HEADER] = requestId;
  }

  const hasBody =
    request.method !== 'GET' && request.method !== 'HEAD' && request.method !== 'DELETE';

  try {
    const backendResponse = await fetch(backendUrl, {
      method: request.method,
      headers,
      body: hasBody ? await request.text() : undefined,
    });
    const body = await backendResponse.text();

    const responseHeaders: Record<string, string> = {
      'Content-Type': backendResponse.headers.get('Content-Type') ?? 'application/json',
    };
    const responseRequestId = backendResponse.headers.get(REQUEST_ID_HEADER);
    if (responseRequestId) {
      responseHeaders[REQUEST_ID_HEADER] = responseRequestId;
    }

    return new NextResponse(body || null, {
      status: backendResponse.status,
      headers: responseHeaders,
    });
  } catch {
    return NextResponse.json({ message: 'Failed to reach backend' }, { status: 502 });
  }
}

export function GET(request: NextRequest, { params }: RouteParams) {
  return proxy(request, params);
}

export function POST(request: NextRequest, { params }: RouteParams) {
  return proxy(request, params);
}

export function PUT(request: NextRequest, { params }: RouteParams) {
  return proxy(request, params);
}

export function DELETE(request: NextRequest, { params }: RouteParams) {
  return proxy(request, params);
}
