import { NextRequest, NextResponse } from 'next/server';
import { UUID_REGEX } from '../../../lib/extractRequestId';

// Full catch-all BFF proxy to the Java backend: every /api/* call the
// browser makes is same-origin against this Next.js app, which forwards it
// on to BACKEND_API_URL server-side. Replaces an earlier version of this
// route that only proxied GET /estado/paginado - that left every other
// call (auth, create/update/delete, actuator/info) going straight from the
// browser to the backend's own origin, which needs CORS enabled there and
// a CSP connect-src naming that origin. Routing everything through here
// removes that requirement entirely.
//
// Deliberately BACKEND_API_URL, not NEXT_PUBLIC_API_URL: a NEXT_PUBLIC_
// var is inlined into the client bundle, so httpClient.ts (running in the
// browser) would read the same value and call the backend directly,
// bypassing this proxy - exactly the CORS/CSP exposure this route exists
// to avoid. Confirmed in production: setting NEXT_PUBLIC_API_URL broke the
// app with connect-src CSP violations and a doubled /estado/estado path
// (httpClient's own /estado prefix on top of the full backend URL).
const REQUEST_ID_HEADER = 'X-Request-Id';

// Shorter than httpClient's 15s timeout on purpose: the proxy has to give up
// first so the client gets a clean 504 it can retry (GET), instead of its own
// timeout firing while this function is still hanging - and billing - on a
// stalled backend.
export const BACKEND_TIMEOUT_MS = 10_000;

// Only what the app actually calls (see src/services/*). This route is a
// public pass-through to the backend, so anything not listed - actuator
// endpoints beyond /info, swagger, heapdump, etc. - is unreachable through
// it even if the backend itself would answer. The regex also rejects any
// '.'/'..' segment, so a `..%2f` in the URL (decoded to '/' by Next) can't
// climb out of BACKEND_API_URL's own path prefix.
const ALLOWED_PATH = /^(estado\/?|estado\/paginado|estado\/\d+|auth\/login|actuator\/info)$/;

// The backend speaks JSON only. Passing through any other Content-Type
// would let it (or anything reflected by it) serve HTML/script from this
// app's own origin - where the app's CSP doesn't apply to /api responses.
const JSON_CONTENT_TYPE = /^application\/([\w.-]+\+)?json\s*(;|$)/i;

// API responses are data, never documents: forbid loading or running
// anything from them, even if a non-JSON body somehow got through.
const API_CSP = "default-src 'none'; frame-ancestors 'none'; sandbox";

interface RouteParams {
  params: Promise<{ path: string[] }>;
}

async function proxy(request: NextRequest, params: RouteParams['params']): Promise<NextResponse> {
  // Read per-request, not module-level: a module-level constant is
  // evaluated once at import time, before tests (or any per-request env
  // override) can set BACKEND_API_URL.
  const backendBaseUrl =
    process.env.BACKEND_API_URL ??
    (process.env.NODE_ENV === 'production' ? undefined : 'http://localhost:8080');
  // No silent localhost fallback in production: a missing env var there is a
  // deploy misconfiguration, and a generic 502 "unreachable" would hide it.
  if (!backendBaseUrl) {
    return NextResponse.json({ message: 'BACKEND_API_URL is not configured' }, { status: 500 });
  }
  const { path } = await params;
  if (!ALLOWED_PATH.test(path.join('/'))) {
    return NextResponse.json({ message: 'Not found' }, { status: 404 });
  }
  const search = request.nextUrl.search;
  const backendUrl = `${backendBaseUrl}/${path.join('/')}${search}`;

  const headers: Record<string, string> = {};
  const authorization = request.headers.get('authorization');
  if (authorization) {
    headers.Authorization = authorization;
  }
  const contentType = request.headers.get('content-type');
  if (contentType) {
    headers['Content-Type'] = contentType;
  }

  // Correlation id generated by httpClient once per user action - it has to
  // reach the backend for its logs to line up with what the client shows.
  const requestId = request.headers.get(REQUEST_ID_HEADER);
  // Only a UUID is forwarded: the value lands in the backend's logs, so an
  // arbitrary string (log injection, markup) is dropped, not passed along.
  if (requestId && UUID_REGEX.test(requestId)) {
    headers[REQUEST_ID_HEADER] = requestId;
  }

  const hasBody =
    request.method !== 'GET' && request.method !== 'HEAD' && request.method !== 'DELETE';

  try {
    const backendResponse = await fetch(backendUrl, {
      method: request.method,
      headers,
      body: hasBody ? await request.text() : undefined,
      signal: AbortSignal.timeout(BACKEND_TIMEOUT_MS),
    });
    const body = await backendResponse.text();

    const contentType = backendResponse.headers.get('Content-Type');
    if (body && !(contentType && JSON_CONTENT_TYPE.test(contentType))) {
      return NextResponse.json({ message: 'Unexpected backend response' }, { status: 502 });
    }

    const responseHeaders: Record<string, string> = {
      'Content-Type': contentType ?? 'application/json',
      'Content-Security-Policy': API_CSP,
    };
    const responseRequestId = backendResponse.headers.get(REQUEST_ID_HEADER);
    if (responseRequestId && UUID_REGEX.test(responseRequestId)) {
      responseHeaders[REQUEST_ID_HEADER] = responseRequestId;
    }

    return new NextResponse(body || null, {
      status: backendResponse.status,
      headers: responseHeaders,
    });
  } catch (error) {
    if (error instanceof DOMException && error.name === 'TimeoutError') {
      return NextResponse.json({ message: 'Backend timed out' }, { status: 504 });
    }
    return NextResponse.json({ message: 'Failed to reach backend' }, { status: 502 });
  }
}

export function GET(request: NextRequest, { params }: RouteParams) {
  return proxy(request, params);
}

export function POST(request: NextRequest, { params }: RouteParams) {
  return proxy(request, params);
}

export function PUT(request: NextRequest, { params }: RouteParams) {
  return proxy(request, params);
}

export function DELETE(request: NextRequest, { params }: RouteParams) {
  return proxy(request, params);
}
